// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA882BI15CtTJZ0zU6VqEpO9WayoFAfQEY',
    appId: '1:727796671408:web:f5de328ab5c46e70182c75',
    messagingSenderId: '727796671408',
    projectId: 'fir-basics-a19a2',
    authDomain: 'fir-basics-a19a2.firebaseapp.com',
    storageBucket: 'fir-basics-a19a2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCVr7sNadbzCcsY7kr4VY6LiccOpXLy1s',
    appId: '1:727796671408:android:34f675ed82461c94182c75',
    messagingSenderId: '727796671408',
    projectId: 'fir-basics-a19a2',
    storageBucket: 'fir-basics-a19a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMr3ftPT6Q4oNZyy48rvbB3mzg8K7kktA',
    appId: '1:727796671408:ios:261b7d36ccda43de182c75',
    messagingSenderId: '727796671408',
    projectId: 'fir-basics-a19a2',
    storageBucket: 'fir-basics-a19a2.appspot.com',
    iosBundleId: 'com.example.fidemo',
  );
}
